site_name: Faxe
theme: material
use_directory_urls: false
extra_css:
  - 'stylesheets/extra.css'
markdown_extensions:
  - codehilite:
        guess_lang: False
        use_pygments: True
        noclasses: True
        pygments_style: monokai
plugins:
  - search
#  - mkpdfs:
#      author: Alexander Minichmair
#  - pdf-export:
#      verbose: false
#      media_type: print
#      enabled_if_env: ENABLE_PDF_EXPORT
#      combined: false